language: node_js
git:
  depth: 1
node_js:
- 11
- 10
- 9
- 8
- 7
- 6
before_script: npm run lint
deploy:
  provider: npm
  skip_cleanup: true
  email: ivo.putzer@gmail.com
  api_key: $NPM_TOKEN
  on:
    repo: ivoputzer/m.test
    tags: false
    branch: master
